---
- name: Install ufw package
  become: true
  ansible.builtin.package:
    name: ufw
    state: present

- name: Enable firewall using ufw
  become: true
  ansible.builtin.command: ufw --force enable

- name: Enable UFW (Uncomplicated Firewall)
  ansible.builtin.command: ufw --force enable

- name: Allow TCP traffic on ports 30303, 30304 and 9000
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  loop:
    - 30303
    - 30304
    - 9000
    - 8080
    - 80
    - 22

- name: Allow UDP traffic on ports 30303, 30304 and 9000
  ufw:
    rule: allow
    proto: udp
    port: "{{ item }}"
  loop:
    - 30303
    - 30304
    - 9000
    - 8080
    - 80
    - 22

- name: Reload UFW
  shell: ufw reload

- name: Enable firewall using ufw
  become: true
  ansible.builtin.command: ufw --force enable
