---
- name: Install HAProxy on ubuntu
  become: true
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy Configuration File
  become: true
  ansible.builtin.template:
    src: ../templates/haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
  register: haproxy_config
  # notify: Restart HAProxy

