---
- name: Check if password file exists
  ansible.builtin.stat:
    path: /root/lighthouse_password.txt
  register: lighthouse_password

- name: Copy random genrated password to password.pass file in /root/lighthouse_password.pass
  when: lighthouse_password.stat.exists == False
  ansible.builtin.template:
    src: ../templates/password.txt.j2
    dest: /root/lighthouse_password.pass

- name: Create consensus system group
  ansible.builtin.group:
    name: consensus
    system: yes

- name: Create consensus system user without home directory
  ansible.builtin.user:
    name: consensus
    group: consensus
    system: yes
    createhome: no

- name: Create directory for Lighthouse data
  become: true
  file:
    path: /var/lib/lighthouse
    state: directory
    owner: consensus
    group: consensus
    mode: '0755'

- name: Download Lighthouse binary
  ansible.builtin.get_url:
    url: "https://github.com/sigp/lighthouse/releases/download/v4.5.0/lighthouse-v4.5.0-x86_64-unknown-linux-gnu-portable.tar.gz"
    dest: "{{ ansible_env.HOME }}/lighthouse-v4.5.0-x86_64-unknown-linux-gnu-portable.tar.gz"

- name: Extract Lighthouse binary
  ansible.builtin.shell:
    cmd: "tar -xvf {{ ansible_env.HOME }}/lighthouse-v4.5.0-x86_64-unknown-linux-gnu-portable.tar.gz"
    chdir: "{{ ansible_env.HOME }}"
  become: true

- name: Copy Lighthouse binary to /usr/bin
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/lighthouse"
    dest: /usr/bin/lighthouse
    mode: '0755'
  become: true

- name: Create lighthouse consensus layer client systemd service file
  become: true
  copy:
    content: |
      [Unit]
      Description=Lighthouse Consensus node for sepolia network
      After=network.target

      [Service]
      ExecStart=/usr/bin/lighthouse beacon_node --datadir /var/lib/lighthouse --network sepolia --checkpoint-sync-url https://sepolia.beaconstate.info --port 9000 --execution-endpoint http://127.0.0.1:8551 --execution-jwt /root/jwt.hex --http --http-port 5052 --http-address 0.0.0.0 --disable-deposit-contract-sync --disable-upnp
      Restart=always 

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/lighthouse.service
  # notify: restart lighthouse

- name: Start and enable the Lighthouse service
  become: true
  systemd:
    name: lighthouse
    state: started
    enabled: yes

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: yes

- name: Enable lighthouse service
  become: true
  systemd:
    name: lighthouse
    enabled: yes

# lighthouse --network sepolia account wallet create --name cube --password-file /root/lighthouse_password.pass
# lighthouse --network sepolia account wallet import --name wally --key-file wally.key --password-file wally.pass

# - name: Check if the file exists
#   ansible.builtin.stat:
#     path: "{{ datadir }}/{{ lighthouse_node_name }}/config/aditional_wallet.txt"
#   register: wallet_file_stat

# - name: Create additional lighthous wallet
#   when: wallet_file_stat.stat.exists == False
#   docker_container:
#     name: additional_lighthous_wallet
#     image: sigp/lighthouse:latest-modern
#     command: account new --password /root/.lighthouse/config/password.txt
#     volumes:
#       - "{{ datadir }}/{{ lighthouse_node_name }}/config:/root/.lighthouse/config"
#     register: additional_wallet

# - name: Copy aditional_wallet details to a file
#   when: additional_wallet.changed
#   ansible.builtin.copy:
#     content: "{{ aditional_wallet.stdout }}"
#     dest: "{{ datadir }}/{{ lighthouse_node_name }}/config/aditional_wallet.txt"
