---
- name: Generate random hex string for jwtsecret and save to file
  ansible.builtin.shell: openssl rand -hex 32 | tr -d '\n' | tee /root/jwt.hex
  become: true


- name: Install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - chrony
    - curl
    - jp
    - ccze

- name: Copy blockchain management scripts to the localhost
  ansible.builtin.copy:
    src: ../files/chain
    dest: /usr/sbin/chain
    owner: root
    group: root
    mode: "a+x"
  tags: chain
  become: true
