---
# handlers for restart geth , lighthouse and haproxy.
- name: restart geth
  ansible.builtin.service:
    name: geth
    state: restarted
  become: true

- name: restart lighthouse
  ansible.builtin.service:
    name: lighthouse
    state: restarted
  become: true
  
- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true