#!/bin/bash

# Script to manage Docker containers ( geth lighthouse haproxy ) on a node

# Function to start all containers
start_containers() {
    echo "Starting all Docker containers..."
    docker start geth lighthouse haproxy
}

# Function to stop all containers
stop_containers() {
    echo "Stopping all Docker containers..."
    docker stop geth lighthouse haproxy
}

# Function to restart all containers
restart_containers() {
    echo "Restarting all Docker containers..."
    docker restart geth lighthouse haproxy
}

# Function to restart all containers
reset() {
    echo "Stop all Docker containers, remove all containers  and removing all containers data..."
    docker stop geth lighthouse haproxy
    sudo rm -rf /root/ethdata/*
    docker start geth lighthouse haproxy
}

# Check the command-line argument
case "$1" in
    start)
        start_containers
        ;;
    stop)
        stop_containers
        ;;
    restart)
        restart_containers
        ;;
    reset)
        reset
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reset}"
        exit 1
        ;;
esac

exit 0
